import { ToastContainer } from 'react-toastify'
import './globals.css'
import { Open_Sans } from 'next/font/google'

const inter = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Creoslab.com',
  description: 'Generated by the Creos Work Force',
  image: 'logo.svg'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
        <ToastContainer />
        </body>
    </html>
  )
}
